### ISSUE TITLE
Flutter Build AAB Not Using Dart-Define

### ISSUE THREAD

**Issue by Vayth** [hey24sheep/vsts-flutter-tasks#11]
I just noticed that when building aab, parameter --dart-define isn't passed

![image](https://user-images.githubusercontent.com/41632555/107463730-51b24680-6b91-11eb-846e-a54b7304d30f.png)

```
  - task: FlutterBuild@0
    inputs:
      target: 'aab'
      projectDirectory: '.'
      buildNumber:
      dartDefine: 'env=prd'
```

It's working nicely on apk, though
