### ISSUE TITLE
Flutter appbundle is not signed

### ISSUE THREAD

**Issue by Vayth** [hey24sheep/vsts-flutter-tasks#13]
I'm not sure whether to write it here or on azure pipeline, but decided to write it here first.

I have an app that use production keystore from Secure Files, then build it as an appbundle.
However, I always get `The Android App Bundle was not signed.` when I'm uploading to Play Store

This is my task
```
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'key.prd.properties'
    displayName: 'Get key.properties from Secure File'

  - task: CmdLine@2
    inputs:
      script: 'mv -v -f key.prd.properties $(Build.SourcesDirectory)/android/key.properties'
      workingDirectory: '$(Agent.TempDirectory)'
    displayName: 'Move key.properties to source code'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'key.prd.keystore'
    displayName: 'Get key.keystore from Secure File'

  - task: CmdLine@2
    inputs:
      script: 'mv -v -f key.prd.keystore $(Build.SourcesDirectory)/android/app/key.keystore'
      workingDirectory: '$(Agent.TempDirectory)'
    displayName: 'Move key.keystore to source code'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'google-services.prd.json'
    displayName: 'Get google-services.json from Secure File'

  - task: CmdLine@2
    inputs:
      script: 'mv -v -f google-services.prd.json $(Build.SourcesDirectory)/android/app/google-services.json'
      workingDirectory: '$(Agent.TempDirectory)'
    displayName: 'Move google-services.json to source code'

  - task: FlutterInstall@0
    inputs:
      channel: 'stable'
      version: 'latest'

  - task: FlutterBuild@0
    inputs:
      target: 'apk'
      projectDirectory: '.'
      splitPerAbi: true
      buildNumber: 
      dartDefine: 'env=prd'
    displayName: 'Building APK'

  - task: CmdLine@2
    inputs:
      script: '$(FlutterToolPath)/flutter build appbundle --release --dart-define=env=prd'
    displayName: 'Building Appbundle'
```

I have tried:
- did `flutter clean` between building apk and aab
- switch order so that aab was built before apk
- remove building apk so that aab was the only one built
- used flutter build task
- changed the agent (`windows-latest`, `ubuntu-latest`, `mac-latest`)

Nothing worked, keep getting that `The Android App Bundle was not signed.`
I verified the apk using `apksigner verify` and it was correctly signed with production key.

However, I can build and sign it alright when I build it on my machine using the same command and the Playstore didn't complain. I wonder if the issue lies in azure pipeline itself or this plugin (maybe when installing through `flutter install`? I'm not sure.

Does anyone have similar experience?

Flutter version is 1.22.6-stable
