### ISSUE TITLE
FlutterBuild use buildNumber from the pipeline build number

### ISSUE THREAD

**Issue by RCSandberg** [hey24sheep/vsts-flutter-tasks#17]
Hi!

Maybe this is intended, and I'm not settings things up correctly. I expected the buildNumber that was going to be used to be `1` because of:
From pubspec.yaml:
`version: 1.0.0+1`

The rest of local.properties, app/build.gradle is unchanged from a new Flutter project.

But it seems like i get the buildNumber from the Azure pipeline.
`/Users/runner/hostedtoolcache/Flutter/2.0.3-stable/macos/flutter/bin/flutter build appbundle --build-number=20210331.10 --dart-define=ENV=dev`

Task is set as follows in the yaml file:
```
- task: FlutterBuild@0
  inputs:
    projectDirectory: $(projectDirectory)
    target: 'aab'
    dartDefine: "ENV=dev"
```

What I could see in the task.json file from the build task is this:
`"defaultValue": "$(Build.BuildNumber)",`

I'm very new to Azure pipelines, so I'm very humble to the fact that I'm messing it up :)

Am I doing something wrong setting this up?

**Comment by RCSandberg** [comment]
I changed the task to look as follows instead, and that did the trick. But should it be this way?
I mean that it defaults to the buildnumber for the pipeline?

`/Users/runner/hostedtoolcache/Flutter/2.0.3-stable/macos/flutter/bin/flutter build appbundle --dart-define=ENV=dev`

```
- task: FlutterBuild@0
  inputs:
    projectDirectory: $(projectDirectory)
    buildNumber: ""
    target: 'aab'
    dartDefine: "ENV=dev"
```

**Comment by hey24sheep** [comment]
Hi,
Yes, by default [build number](https://github.com/hey24sheep/vsts-flutter-tasks/blob/3d87929c26e07ef0b9e9ea58440acc22e9ab48f8/tasks/build/task.json#L92) is used for ease of use/setup (intended that way cuz flutter versioning was introduced later). You can make it empty like you did to get flutter versioning. Let me know if you have any issues.

**Comment by RCSandberg** [comment]
Ran into a new issue. Should I create a separate issue here for that?
I tried adding extraArgs, obfuscation in my case. Set it as follows:

`extraArgs: '--obfuscate --split-debug-info=build/debug_symbols'`

It seems to produce the correct output, at least according to outputted log:

`/Users/runner/hostedtoolcache/Flutter/2.0.3-stable/macos/flutter/bin/flutter build appbundle --dart-define=ENV=dev --obfuscate --split-debug-info=build/debug_symbols`

However, I get the following error:
`Target file "--obfuscate --split-debug-info=build/debug_symbols" not found.`

Running the same command locally on my machine with a clean directory, i.e. build/debug_symbols is missing, works fine. The directories are created as it should. I've tested locally on both mac and windows.

**Comment by hey24sheep** [comment]
Seems like the right command. It should work, have a look [here](https://stackoverflow.com/questions/61976886/how-to-use-split-debug-info-project-name-directory).

**Comment by hey24sheep** [comment]
Try running `$(FlutterToolPath)/flutter clean` before build task

**Comment by RCSandberg** [comment]
It shouldn't make any difference since everything is clean, new checkout from repo etc, each time the pipeline is triggered.
But I tested it anyway. I ran flutter clean before the build task. Same outcome, unfortunately.

BUT, instead of the following task:
```
- task: FlutterBuild@0
  inputs:
    projectDirectory: $(projectDirectory)
    buildNumber: ""
    target: 'aab'
    dartDefine: "ENV=dev"
    extraArgs: '--obfuscate --split-debug-info=$(outputsSubDir)/$(debugSymbols)'
```

I tried to run the following task:
```
- task: CmdLine@2
  inputs:
    script: '$(FlutterToolPath)/flutter build appbundle --dart-define=ENV=dev --obfuscate --split-debug-info=$(outputsSubDir)/$(debugSymbols)'
```

The first fails:
`Target file "--obfuscate --split-debug-info=build/app/outputs/debug_symbols" not found.`

The second succeeds:
`✓ Built build/app/outputs/bundle/release/app-release.aab (14.7MB).`

Soooo, something with FlutterBuild@0 misbehaves...
